encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.goto, name="title"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/", views.edit, name="edit"),
    path("editreal/", views.editreal, name="editreal"),
    path("random/", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.
class WForm(models.Model):
    title = models.CharField(max_length=100, verbose_name="")
    content = models.CharField(max_length=1000000, verbose_name="")

encyclopedia/forms.py
from django.forms import ModelForm, TextInput, Textarea
from encyclopedia.models import WForm

class CreateForm(ModelForm):
    class Meta:
        model = WForm
        fields = ('title', 'content')

        widgets={
            'title': TextInput(attrs={
                 'name': 'title',
                 'label': '',
                 'placeholder': 'Enter Title Here', 
                 'style': 'width: 80%; margin-top: 20px;',
            }),
            'content': Textarea(attrs={
                'name': 'content', 
                'placeholder': 'Type your content here',
                 'style': 'margin-top: 20px;'
            })
        }
    

class EditForm(ModelForm):
    class Meta:
        model = WForm
        fields = ('title', 'content')

        widgets={
            'title': TextInput(attrs={
                 'name': 'title',
                 'label': '',
                 'placeholder': 'Enter Title Here', 
                 'style': 'width: 80%; margin-top: 20px;',
            }),
            'content': Textarea(attrs={
                'name': 'content', 
                'placeholder': 'Type your content here',
                 'style': 'margin-top: 20px;'
            })
        }
    def fill(self, title, content):
        self.title = title
        self.content = content
        return [self.title]

encyclopedia/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template import Context, Template
from . import util
from encyclopedia.forms import CreateForm, EditForm
import json
import re
import random



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def goto(request, title):
    content = util.converted_entry(title)
    if (content is None):
        return render(request, "encyclopedia/error.html")
    return render(request, "encyclopedia/goto.html", {
        "content": content,
        "title": title,
        "text": content,
    })

def search(request):
    bite = request.body
    encoding = 'ISO-8859-1'
    stringedQuery = bite.decode(encoding)
    query = stringedQuery.split('=')
    entries = util.search_entries(query[2])
    
    content = util.get_entry(query[2])
    
    if entries == []:
        return render(request, "encyclopedia/error.html")

    if content:
        return render(request, "encyclopedia/goto.html", {
            "content": content, 
        })                                  
    else:
        return render(request, "encyclopedia/search.html", {
            "title": query[2],
            "entries": entries,
        })

def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            
            if (util.get_entry(title)):
                messages.error(request, f"An entry with the title {title} already exists. Please choose another title.")
            else:
                util.save_entry(title, content)
                return goto(request, title)
    return render(request, "encyclopedia/create.html", {
        "all": CreateForm()
    })


def edit(request):
    if request.method == 'POST':
        data = request.POST
        content = util.get_entry(data['title'])
        form = EditForm(initial={'title': data['title'], 'content': content})
        return render(request, 'encyclopedia/edit.html', {
            "title": data['title'],
            "all": form,
        })
    
def editreal(request):
    if request.method == 'POST':
        data = request.POST
        util.save_entry(data['title'], data['content'])
        return goto(request, data['title'])

def randomPage(request):
    listEntries =  util.list_entries()
    randomMd = random.choice(listEntries)

    return goto(request, randomMd)

def markdownify(title):
    # opening file \[(.*)\]\(/wiki/(.*)\)
    with open(f"entries/{title}.md") as file:
        # reading into the file
        reading_file = file.read()
        # converting markdown heading to html heading
        for i in range(6, 0, -1):
            reading_file = re.sub(fr"{'#' * i}(.*)", fr"<h{i}>\1</h{i}>", reading_file)
            
        # converting markdown boldface text into html boldface text
        reading_file = re.sub(r'\*\*(.*?)\*\*', r"<b>\1</b>", reading_file)

        # converting markdown italic into html italic text
        reading_file = re.sub(r'_(.*?)_', r"<i>\1</i>", reading_file)
        reading_file = re.sub(r'\*(.*?)\*', r"<i>\1</i>", reading_file)  

        # converting markdown unordered lists into html unordered lis  
        reading_file = re.sub(r'[-+*]\s+(.*)', r'<li>\1</li>', reading_file, flags=re.MULTILINE)
        
        reading_file = re.sub(r'(<li>.*</li>)', fr'<ul>\1', reading_file, 1) 
        reading_file = re.sub(r'</li>(?![\s\S]*</li>)', '</li></ul>', reading_file)  

        # converting markdown links into html links
        reading_file = re.sub(r'\[(.*?)\]\((.*?)\)', r'''<a href="\2">\1</a>''', reading_file)

        # add a paragraph tag
        # reading_file = re.sub(r"(The most.*)", r"<p>\1</p>", reading_file, flags=re.DOTALL)

        return reading_file 

encyclopedia/templates/encyclopedia/create.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
{% if messages %}
{% for message in messages %}
  <div class="alert alert-dismissible {{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert">
    ×
    </button>
    <strong>{{message}}</strong>
  </div>
{% endfor %}
{% endif %}
    <h1>Create a markdown page</h1>
    <form action="{% url 'wiki:create'%}" method="post">
        {% csrf_token %}
        {{all}}
        <input type="submit" class="btn-primary btn" style="display: block; margin-top: 20px;" value="Create Page">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
{% if messages %}
{% for message in messages %}
  <div class="alert alert-dismissible {{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert">
    ×
    </button>
    <strong>{{message}}</strong>
  </div>
{% endfor %}
{% endif %}
    <h2>Editing {{title}}</h2>
    <form action="{% url 'wiki:editreal' %}" method="post">
        {% csrf_token %}
        {{all}}
        <input type="submit" class="btn-primary btn" style="display: block; margin-top: 20px;" value="Confirm Edit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<h1 style="color: crimson">ERROR: FILE NOT FOUND</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/goto.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
    {{ content|safe }}
    <form action="{% url 'wiki:edit' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="title" value="{{title}}" id="">
    <input type="hidden" name="content" value="{{text}}" id="">
    <input type="submit" id="submit-button" value="Edit" class="btn-primary btn" style="display:block; margin-top: 20px;">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2><a href="{% url 'wiki:index' %}">Wiki</a></h2>
                <form action="{% url 'wiki:search' %}" method="post">    
                {%csrf_token%}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
     <h1>"{{title}}"</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}